language: android
android:
  components:
    - android-28
    - build-tools-28.0.2

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=15

before_install:
    - echo yes | sdkmanager "build-tools;28.0.2"

# Run assemble and unit tests
script:
  - ./gradlew clean assembleDebug assembleRelease testDebug