sudo: false
language: android
jdk:
  - oraclejdk8
env:
  global:
    - ANDROID=28
    - ANDROID_BUILD_TOOLS=28.0.2
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID
before_install:
  - yes | sdkmanager "platforms;android-$ANDROID"
script:
  - ./gradlew clean build
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      ./gradlew uploadArchives -PSONATYPE_USERNAME="${SONATYPE_USERNAME}" -PSONATYPE_PASSWORD="${SONATYPE_PASSWORD}";
    fi
